# Generated by Django 3.2.8 on 2021-10-13 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='process',
            name='done',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3),
        ),
    ]
